### ISSUE TITLE
Validate EpiRR record if 'experiment_type' is not present

### ISSUE THREAD

**Issue by zxenia** [IHEC/ihec-ecosystems#42] opened 2019-08-29 19:38 UTC
Schema experiment.json requires 'experiment_type' or 'experiment_ontology_uri'. When validating EpiRR record 'experiment_type' is required for an error message.  Need to resolve it to a valid experiment type or to an experiment ontology uri / term.

**Comment by dzerbino** [comment] 2019-08-30 09:04
Hello @zxenia, 

Thanks for raising this. 

Just to be clear, does this require a fix in the validator? Could you deal with it?

Cheers,

Daniel

**Comment by dbujold** [comment] 2019-08-30 13:13
Hi Daniel, it will be difficult to validate a data hub with the EpiRR record when an experiment_ontology_uri is provided instead of an experiment_type. The problem is that there will be no way to make a match between the experiment in the data hub and the experiment in the EpiRR record. Perhaps a solution would be to require the experiment ID in the data hub to match the primary ID in the EpiRR record?

**Comment by dzerbino** [comment] 2019-08-30 13:47
Sounds reasonable. Is this not the case already?

**Comment by dbujold** [comment] 2019-08-30 14:23
It's never been specified in a spec document, AFAIK. Some groups do that already but not all.

**Comment by dzerbino** [comment] 2019-08-30 14:54
Seems like a reasonable request.

**Comment by sitag** [comment] 2019-08-30 18:16
You will have problems here. There can be multiple primary ids in the epirr for an experiment, but only one track that represents it there (e.g. a merge). We can add that as a list of attributes but you cannot use that as the key, since it may not be unique.    

As an aside, lets not couple an implementation details into the logic of the spec.  I agree through that mapping between experiments of the two records should exist; but its not 1:1.

**Comment by dzerbino** [comment] 2019-09-03 15:47
Summary of phone call on 3/9/2019: 

There is an issue of insufficient metadata in the portal JSON submission in the case of experiments with identical epigenome ID and assay type. This does not block the EpiMap analysis, but is annoying for the portal's traceability.

**Comment by sitag** [comment] 2019-09-19 04:36
@dzerbino okay ..so what are we doing/who is doing it?

**Comment by dzerbino** [comment] 2019-09-19 14:40
At the last call we did not have a clear solution forward.

To me the most straightforward solution would simply require the portal submission to contain both EpiRR IDs for epigenomes and external (e.g. EGA) IDs for each experiment.

**Comment by dbujold** [comment] 2019-09-23 20:45
That would work, I think.

**Comment by sitag** [comment] 2019-09-24 08:09
@dzerbino  @dbujold I am little confused how does this cross referencing solves the issue? Are you going to look up the experiment_id in epirr and pull experiment_type from there? 
We could also just look up the uri and get the associated experiment. 

We use the same schema for validating what goes into EpiRR. Why would you expect it to have experiment type there?

Is the issue just being able to template an error message: `When validating EpiRR record 'experiment_type' is required for an error message` or is it more fundamental?

**Comment by dzerbino** [comment] 2019-09-25 04:00
The problem we are trying to solve is that we can have technical replicates experiments that lead to multiple tracks on the portal but are indifferentiable using IHEC IDs and experiment type alone. Providing explicit EGAXs in the portal submission mean that the portal can a) provide the tracks with unique labels and b) give the user a modicum of traceability. 

In other words, from the experiment type is necessary but not sufficient for the needs of the portal.

**Comment by sitag** [comment] 2019-09-25 05:57
@dzerbino That was the discussion on the call which was very high level; I am note sure how it solves issue reported by @zxenia

> Schema experiment.json requires 'experiment_type' or 'experiment_ontology_uri'. When validating EpiRR record 'experiment_type' is required for an error message. Need to resolve it to a valid experiment type or to an experiment ontology uri / term.

Where in the spec will this identifiers go, and how will this be used in the validator? 
Someone will need to pin this down so it can be implemented. 

@zxenia @dbujold It would be nice if we follow https://stackoverflow.com/help/minimal-reproducible-example idea here... provide a json that had this problem. Then we have a test for any solution we come up with.

**Comment by zxenia** [comment] 2019-09-25 21:35
Here I summarized the initial problem I encountered.

The schema for experiment states:

```
{"anyOf": [
            {"required": ["experiment_ontology_uri", "library_strategy"]},
            {"required": ["experiment_type", "library_strategy"]}
        ]
}
```

When running validator and 'experiment_type' is not present in example json, I get a KeyError:

```
File "validateHub.py", line 182, in validateEpirr
    exp_name = exp_attr['experiment_type']
KeyError: 'experiment_type'
```
Further in code `exp_name` is used for the error message:

IHEC_Data_Hub/validateHub.py:212
```
if exp_name.lower() not in raw_data_per_exp:
         logging.getLogger().error('-Experiment "%s" could not be found in EpiRR record %s.' % (exp_name, epirr_id))
```
The default value for 'experiment_type' is not defined if it's not present (which is allowed by schema).
On my branch, I just add _else_ to escape the error - to take 'experiment_ontology_uri' if 'experiment_type' is not present because one of them must be present.

Based on your comments I understand that the issue is more complex. So I suggest just to fix the validator error message for now.

**Comment by sitag** [comment] 2019-09-25 21:49
@zxenia @dbujold @dzerbino 

I suppose `logging.getLogger().error('-Experiment "%s" could not be found in EpiRR record %s.' % (exp_name, epirr_id)` is where you wanted to match epirr to the datahub experiment? 
 
I agree with @zxenia  and just fixing the error message. 

The discussion about matching epirr to datahub is separate, and beyond the scope of this bug. It deserves it's own separate issue.

**Comment by dbujold** [comment] 2019-09-26 13:52
I'm ok to split this to another issue.

**Comment by dbujold** [comment] 2019-09-26 13:58
Just created issue #50 .

**Comment by sitag** [comment] 2019-09-26 17:19
@zxenia your solution sounds great. please close this whenever it gets merged - we can do it with https://github.com/IHEC/ihec-ecosystems/pull/41

**Closed** 2020-02-03 16:12 UTC
Labels: PR under discussion
